### ISSUE TITLE
Response no longer highlights syntax

### ISSUE THREAD

**Issue by chaucerbao** [diepm/vim-rest-console#44]
I've noticed that the response window no longer has its syntax highlighted.

![image](https://user-images.githubusercontent.com/794434/26848918-054ef936-4ab7-11e7-9239-e00b9d79109a.png)

However, I can run a `:set ft=rest` on the `__REST_response__` window to restore highlighting.

![image](https://user-images.githubusercontent.com/794434/26848975-3fe0543c-4ab7-11e7-877d-0405ea678c2e.png)

**Comment by diepm** [comment]
Do you have `g:vrc_curl_opts` (with `-i`) or `g:vrc_include_response_header` (or `b:vrc_include_response_header`) set? I'm curious because your response comes with the headers while your request doesn't specify any curl options. It might or might not be a bug depending on those settings.

You can enable the debug mode and check what cUrl options are used with your request.

**Comment by chaucerbao** [comment]
This is my config for VRC. Just one(-ish).

```
let g:vrc_curl_opts={
	\'--include': '',
	\'--location': '',
	\'--show-error': '',
	\'--silent': ''
\}
```

**Comment by chaucerbao** [comment]
Oh, and removing cURL's `-i` option still doesn't enable the syntax highlighting.

![image](https://user-images.githubusercontent.com/794434/26866886-f37ba87e-4b17-11e7-8ff0-f1b73f900127.png)

I'm thinking that **syntax/rest.vim** works, but just isn't being applied.

**Comment by diepm** [comment]
I see what went wrong. Just pushed the fix. Please retest. Thanks!

**Comment by chaucerbao** [comment]
Works for `--include` and `-i` now!

However, there's no syntax highlighting if you're **not** using `--include`/`-i`.

*By the way, thanks a lot for your work on this plugin. I like being able to stay in Vim to test APIs instead of constantly switching apps.*

**Comment by diepm** [comment]
It's expected since without the returned headers, VRC doesn't know the content type to properly format or syntax-highlight the content. However, there are a couple ways if you don't want to include the `--include`/`-i` flag. Check out section 7.2 and option `vrc_response_default_content_type`.

Glad that you enjoy VRC!

**Comment by chaucerbao** [comment]
Makes sense. I'm used to assuming JSON by default.
